{{- if and .Values.secret.dbSecret.enabled (not .Values.aws.secretmanager.enabled) (not .Values.azure.keyvault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.dbSecret.name }}
  namespace: {{ .Values.namespaces.nexusNs }}
type: Opaque
stringData:
  db-host: {{ .Values.secret.db.host }}
  db-user: {{ .Values.secret.db.user }}
  db-password: {{ .Values.secret.db.password }}
{{- end }}
