apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.nexusNs }}
---
{{- if .Values.aws.enabled }}
{{- if .Values.fluentbit.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.cloudwatchNs }}
{{- end }}
---
{{- if .Values.externaldns.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.externaldnsNs }}
{{- end }}
{{- end }}
---
