{{- if and .Values.secret.nexusAdminSecret.enabled (not .Values.aws.secretmanager.enabled) (not .Values.azure.keyvault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.nexusAdmin.name }}
  namespace: {{ .Values.namespaces.nexusNs }}
type: Opaque
stringData:
  nexus-admin-password: {{ .Values.secret.nexusAdminSecret.adminPassword }}
{{- end }}