{{- if .Values.storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ .Values.storageClass.name }}"
  namespace: {{ .Values.namespaces.nexusNs }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  type: {{ .Values.storageClass.type }}
  fsType: "{{ .Values.storageClass.fsType }}"
  iopsPerGB: "{{ .Values.storageClass.iopsPerGB }}"
volumeBindingMode: WaitForFirstConsumer
{{- end }}